# Generated by Django 4.2 on 2024-03-20 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('about', models.TextField(blank=True, verbose_name='About (Optional)')),
                ('contact_email', models.CharField(max_length=200, verbose_name='Contact Email')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(verbose_name='Project Description')),
                ('portfolio', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='music_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, verbose_name='UCCS Email')),
                ('genre', models.CharField(choices=[('Rock', 'Rock'), ('Pop', 'Pop'), ('Christian/Worship', 'Christian/Worship'), ('Classical', 'Classical'), ('Indie', 'Indie'), ('Jazz', 'Jazz'), ('Instrumental', 'Instrumental')], max_length=200)),
                ('instrument', models.CharField(max_length=200)),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='music_app.profile')),
            ],
        ),
    ]
