# Generated by Django 4.2 on 2024-03-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='portfolio',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='artist',
            name='email',
            field=models.CharField(max_length=200, verbose_name='artist email'),
        ),
    ]
