# Generated by Django 4.2 on 2024-04-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_rename_portfolio_project_profile_alter_artist_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_active',
            new_name='is_public',
        ),
        migrations.AlterField(
            model_name='artist',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='artist email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_email',
            field=models.EmailField(max_length=50, verbose_name='Contact Email'),
        ),
    ]
