# Generated by Django 4.2 on 2024-02-27 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_delete_user_alter_portfolio_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.student'),
        ),
    ]
