# Generated by Django 4.2 on 2024-04-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0006_user_artist_alter_user_password1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='password1',
            field=models.CharField(default='change this', max_length=200, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='artist',
            name='password2',
            field=models.CharField(default='change this', max_length=200, verbose_name='confirm password'),
        ),
        migrations.AddField(
            model_name='artist',
            name='username',
            field=models.CharField(default='username here', max_length=200),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
