# Generated by Django 4.2 on 2024-03-05 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_remove_student_portfolio_portfolio_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='portfolio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.portfolio'),
        ),
        migrations.AlterField(
            model_name='project',
            name='portfolio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.portfolio'),
        ),
    ]
