# Generated by Django 4.2 on 2024-04-09 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_app', '0007_artist_password1_artist_password2_artist_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='password2',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='username',
        ),
        migrations.AddField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
