# Generated by Django 4.2 on 2024-04-09 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('music_app', '0008_remove_artist_password1_remove_artist_password2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='user',
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('artist', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='music_app.artist')),
                ('groups', models.ManyToManyField(related_name='users', related_query_name='user', to='auth.group')),
            ],
        ),
    ]
