# Generated by Django 4.2 on 2024-04-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0010_artist_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mp3_file',
            field=models.FileField(blank=True, default='/static/audio/default_audio.mp3', null=True, upload_to='static/audio/'),
        ),
    ]
