# Generated by Django 4.2 on 2024-04-15 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0011_project_mp3_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(verbose_name='Post Description')),
                ('mp3_file', models.FileField(blank=True, default='/static/audio/default_audio.mp3', null=True, upload_to='static/audio/')),
                ('profile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='music_app.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
