# Generated by Django 4.2 on 2024-04-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0013_alter_post_mp3_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mp3_file',
            field=models.FileField(blank=True, default='audio/mp3/default_audio.mp3', upload_to='audio/mp3/'),
        ),
    ]
