# Generated by Django 4.2 on 2024-04-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0014_alter_post_mp3_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mp4_file',
            field=models.FileField(blank=True, default='video/mp4/default_video.mp4', upload_to='video/mp4/'),
        ),
    ]
