name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11.7]

    steps:
    - name: Setup Python
      uses: actions/setup-python@master
      with: 
        python-version: 3.11.7
    
    - name: Run Tests
      
      run: |
        pip install coverage
        pwd
        cd profile/
        coverage run --source=music_app/profile manage.py test music_app.tests_folder.unit_tests
