name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.11.7
      uses: actions/setup-python@v2
      with: 
        python-version: 3.11.7

    - name: Install dependencies
      run: |
        py -3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8
    
    - name: Coverage Tests and Report
      run: |
        pip install coverage
        pwd
        coverage run manage.py test music_app.tests_folder.unit_tests
        coverage report

    
