name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.11.7
      uses: actions/setup-python@v2
      with: 
        python-version: 3.11.7
    
    - name: Coverage Tests and Report
      run: |
        pip install coverage
        pwd
        coverage run manage.py test music_app.tests_folder.unit_tests
        coverage report

    
