name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.11.7
      uses: actions/setup-python@v2
      with: 
        python-version: 3.11.7

    - name: Install dependencies
      run: |
        pip install coverage
        pip install django==4.2

    - name: Activate Virtual Environment
      run: |
        pwd
        ls -la  # List all files in the current directory for debugging purposes
        echo $GITHUB_WORKSPACE
        cd /home/runner/work/cs3300-webapp/cs3300-webapp/profile # Change directory to your Django project root
        source djvenv/Scripts/activate
    
    - name: Coverage Tests and Report
      run: |
        pwd
        ls -la  # List all files in the current directory for debugging purposes
        cd /home/runner/work/cs3300-webapp/cs3300-webapp/profile  # Change directory to your Django project root
        coverage run manage.py test music_app.tests_folder.unit_tests
        coverage report

    
